server:
  port: 8080
spring:
  profiles:
    include: oauth
  application:
    name: jpa
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: springjjang052
    password: 1234
  security:
    user:
      name: jjang051
      password: 1234
      roles: ADMIN


  #mybatis:
#  config-location: classpath:mybatis/config/config.xml
#  mapper-locations: classpath:mybatis/mapper/**/*.xml
#  type-aliases-package: com.jjang051.board02.dto
#  error / warn / info / debug / trace
  logging:
    level:
      org.springframework: info
      org.hibernate.sql : debug
      root: info
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB

  mail:
    host: smtp.naver.com
    port: 465
    username: jjang051@naver.com
    password: UJ1MNGBVSXFP
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust:  smtp.naver.com
        debug: true

file:
  path: D:\upload\
